# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f99685c9a9d7324071ea016441a434bce41808a3e9801cd25fe3c395fc3d8fad7e91bac74f68eaaafa708849c0845b0a8d4602eec459f92fe44cba34bb45369

test:
  secret_key_base: 40f9cfe7c6159e0441c1f6f3b44859780daddebff1cd592777ecdd5470ce88ff250a1a8386c3fd7a5175185c3aefa1f5c0c62f180c39f97ada59917f20300aa6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

